### ISSUE TITLE
Dosocs2 won't do a oneshot scan on ubuntu 15.10 - gnome3 version

### ISSUE THREAD

**Issue by jmoseman01** [socs-dev-env/dosocs2#78] opened 2016-02-15 19:51 UTC
```
jesse@jesse-Aspire-V5-571P:~/Documents/myproject$` dosocs2 oneshot openssl-1.0.1r.tar.gz 
dosocs2: openssl-1.0.1r.tar.gz: package_id: 1
dosocs2: running nomos on package 1
Traceback (most recent call last):
  File "/usr/local/bin/dosocs2", line 9, in <module>
    load_entry_point('dosocs2==0.16.0', 'console_scripts', 'dosocs2')()
  File "/usr/local/lib/python2.7/dist-packages/dosocs2-0.16.0-py2.7.egg/dosocs2/dosocs2.py", line 325, in main
    package = do_scan(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dosocs2-0.16.0-py2.7.egg/dosocs2/dosocs2.py", line 141, in do_scan
    scanner.run(**scanner_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dosocs2-0.16.0-py2.7.egg/dosocs2/scannerbase.py", line 124, in run
    if self.ignore_pattern is not None:
AttributeError: 'Nomos' object has no attribute 'ignore_pattern'
jesse@jesse-Aspire-V5-571P:~/Documents/myproject$ 
```

**Comment by jmoseman01** [comment] 2016-02-15 19:54
jesse@jesse-Aspire-V5-571P:~/Documents/myproject$ dosocs2 configtest

---

Config location:
/home/jesse/.config/dosocs2/dosocs2.conf (not present)

---

Effective configuration:

# begin dosocs2 config

connection_uri = sqlite://///home/jesse/.config/dosocs2/dosocs2.sqlite3
default_scanners = nomos
echo = False
namespace_prefix = sqlite:////home/jesse/.config/dosocs2/dosocs2.sqlite3
scanner_nomos_path = /usr/local/share/fossology/nomos/agent/nomossa

# end dosocs2 config

---

Testing specified scanner paths...
nomos (/usr/local/share/fossology/nomos/agent/nomossa)...ok.

---

Testing database connection...ok.

**Comment by ghost** [comment] 2016-02-15 20:14
Looks like a duplicate of #72

The fix for this was just merged into master today with a88069b . Try cloning the latest version of master and see if you run into the same problem.

**Comment by ghost** [comment] 2016-02-15 20:15
@ttgurney  thank you. 

@jmoseman01 use `dosocs2 newconfig -f <location_to_write_to>`  to write configuration

**Comment by ghost** [comment] 2016-02-15 20:21
@jmoseman01 closing issue, please reopen if issue persists.

**Closed as completed** 2016-02-15 20:21 UTC

**Comment by jmoseman01** [comment] 2016-02-15 20:34
Thanks!  I was running off of v16 tar.gz file not the repo.....

**Comment by ghost** [comment] 2016-02-15 20:43
@jmoseman01 thanks for pointing this out, I will create a new release.
